#!/bin/bash
# Cross-compile executable for ARM platform then push this to a
# Raspberry Pi.
# Assumes you've set up suitable SSH keys on local machine and remote Pi.
TARGET_USER=Pi			# username on target pi
TARGET_HOST=ada.local	# hostname or IP of target Pi
TARGET_DIR=code			# sub-dir below user's home dir
ARM_VERSION=7			# suitable for Pi 2 or 3. Use 6 for other models of Pi

# Executable name is assumed to be same as current directory name
EXECUTABLE=${PWD##*/}
echo "Executable: $EXECUTABLE"

echo "Building for Raspberry Pi..."
env GOOS=linux GOARCH=arm GOARM=$ARM_VERSION go build

echo "Uploading to Raspberry Pi:"
echo "    host: $TARGET_HOST"
echo "    user: $TARGET_USER"
echo "    dir : $TARGET_DIR"
scp -i ~/.ssh/ssh-key $EXECUTABLE $TARGET_USER@$TARGET_HOST:$TARGET_DIR/$EXECUTABLE
